### PR TITLE
Updating PredictionIOTests, PIOItemRecGetTopNRequest, PIOItemSimGetTopNRequest

### PR DESCRIPTION
**Pull request by agrinman**
**PredictionIOTests**
Added basic functionality tests for the remainder of the SDK methods. 

**PIOItemRecGetTopNRequest** and *\* PIOItemSimGetTopNRequest**
Fixed a bug in the request params logic for attributes

### CODE REVIEW

**Comment by yf225** [comment]
Thanks so much for finishing up the SDK! Just wondering did you try running the test methods on a  PIO server? I didn't manage to get the engine started locally but I can help with testing those that won't require a working engine.

**Comment by agrinman** [comment]
No problem, I'm glad to help! 
Yes, I ran the test methods on a local PIO server on my machine. I set up the Rec and Sim engines and all the test methods successfully do requests to the server and return the correct results.

**Comment by yf225** [comment]
That's awesome! What do you think would be the next step? Should we work on a demo app or write a tutorial for the SDK? I guess a lot of people are not very familiar with AFNetworking's callback paradigm and might need a little help on that part. Otherwise our SDK seems very straightforward and also very similar to other drivers such as Java's.

**Comment by k4hoo** [comment]
Great work guys! Thanks Alex and Yanbin!
Yes. Building a demo app to show how to use this SDK would be our next goal.
At the same time, would like to see if anything can be improved in the current SDK to make it more iOS-developer friendly?

By the way, we can move future discussion to google dev group:
https://groups.google.com/forum/#!forum/predictionio-dev

**Comment by agrinman** [comment]
Sorry for the delayed response (it was a busy week). I posted an idea for a possible improvement here:

https://groups.google.com/d/msg/predictionio-dev/t5iMUPrEFnA/J4k6x3HtGVoJ

In addition to this, I would  also like to start working on the demo app. Are there any standard sample app ideas I should build for iOS. My idea was to start off developing a very simple food recommendation app. The current idea is to have a list of foods and each food can be 'viewed'. On the view screen, the food item can be liked, disliked, rated, etc.. The app will have several users you can switch between, and for each user there will be a button to view a list of food recommendations for the user. Also, every time the user selects a food, the user will see similar foods.

**Comment by k4hoo** [comment]
I think it's a great idea! Do you know any public data set about food can be used?

**Comment by agrinman** [comment]
I was planning on just making my own 10-15 foods. Do you think a larger data set is better? I can also substitute foods with movies or another similar entity that I can find a good public data set for.

**Pull request merged**
